### PR TITLE
set default PERL_MACH for aarch64 build

### PR DESCRIPTION
**Pull request by hadfl**

### CODE REVIEW

**Comment by richlowe** [comment]
I'd prefer somehing like this again:

```diff
diff --git a/usr/src/Makefile.master b/usr/src/Makefile.master
index e785a8bc4d..980895a425 100644
--- a/usr/src/Makefile.master
+++ b/usr/src/Makefile.master
@@ -217,8 +217,10 @@ FIND=              /usr/bin/find
 PERL=          /usr/bin/perl
 PERL_VERSION=  5.10.0
 PERL_PKGVERS=  -510
-PERL_MACH=     i86pc
-$(SPARC_BLD)PERL_MACH= sun4
+i386_PERL_MACH=         i86pc
+sparc_PERL_MACH= sun4
+aarch64_PERL_MACH= aarch64
+PERL_MACH = $($(NATIVE_MACH)_PERL_MACH)
 PERL_VARIANT=
 PERL_ARCH=     $(PERL_MACH)-solaris$(PERL_VARIANT)-64int
 PERL_ARCH64=   $(PERL_MACH)-solaris$(PERL_VARIANT)-64
 ```

But what I'm confused by is why (based on your diff, and what we did before) that we leave it as x86 when we're cross compiling, is that really correct?

**Comment by hadfl** [comment]
Yeah this is confusing. I'll put this PR on draft until I have answers.

**Comment by hadfl** [comment]
I got confused because I have `PERL_ARCH` set in the env file for cross compiling and forgot. I think we should have a sane default for `aarch64` in `Makefile.master` as well like we do for other arch. That's exactly what your diff above does.

**Comment by richlowe** [comment]
Based on what you said, my diff uses `NATIVE_MACH` where it should use `MACH`

**Comment by hadfl** [comment]
> Based on what you said, my diff uses `NATIVE_MACH` where it should use `MACH`

You are right.

**Pull request merged**
