### PR TITLE
Fix circular dependency in tools/svc/libscf

### PR DESCRIPTION
**Pull request by b-man**
This change resolves a circular dependency in bldtools where during a non-incremental build tools/svc/libscf fails to compile due to missing libzonecfg.h in the sysroot, but the sysroot has not been populated yet as the bldtools and sgs targets need to complete before the sysroot headers are populated.

Environment: OmniOS and OpenIndiana

Build error:

```
omnios --> Job output
/home/brian/Development/arm64-gate/illumos-gate/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw  --primary gcc10,/opt/gcc-10/bin/gcc,gnu  --shadow gcc7,/opt/gcc-7/bin/gcc,gnu -- -O -m32 -fpic  -errtags=yes -errwarn=%all -_gcc=-Wno-missing-braces -_gcc=-Wno-sign-compare -_gcc=-Wno-unknown-pragmas -_gcc=-Wno-unused-parameter -_gcc=-Wno-missing-field-initializers -_gcc=-Wno-array-bounds -_smatch=-p=illumos_user -_smatch=--disable=uninitialized,check_check_deref -_smatch=-Wno-vla -_smatch=-Wno-one-bit-signed-bitfield -_smatch=-Wno-external-function-has-definition -_smatch=-Wno-old-style-definition -_smatch=-Wno-strict-prototypes -_smatch=--fatal-checks -_smatch=--timeout=0  -_smatch=off -_gcc=-Wno-switch -_gcc=-Wno-char-subscripts -_gcc=-Wno-unused-label -_gcc=-Wno-parentheses -_gcc=-Wno-maybe-uninitialized -xc99=%none -_gcc=-fno-inline-small-functions  -_gcc=-fno-inline-functions-called-once  -_gcc=-fno-ipa-cp  -_gcc=-fno-ipa-icf  -_gcc=-fno-clone-functions  -_gcc=-fno-reorder-functions  -_gcc=-fno-reorder-blocks-and-partition -_gcc=-fno-aggressive-loop-optimizations -_gcc=--param=max-inline-insns-single=450    -g -_gcc=-gdwarf-2 -_gcc10=-gstrict-dwarf -_gcc11=-gstrict-dwarf -xc99=%none -D_TS_ERRNO -DNATIVE_BUILD -DTEXT_DOMAIN=\"SUNW_OST_OSLIB\"  -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/inc -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/common/svc -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libuutil/common  -I/home/brian/Development/arm64-gate/illumos-gate/proto/root_aarch64/usr/include -DPIC -D_REENTRANT -c -o pics/lowlevel.o /home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/common/lowlevel.c
+ /opt/gcc-10/bin/gcc -fident -finline -fno-inline-functions -fno-builtin -fno-asm -fdiagnostics-show-option -nodefaultlibs -D__sun -O -m32 -fpic -Wall -Wextra -Werror -Wno-missing-braces -Wno-sign-compare -Wno-unknown-pragmas -Wno-unused-parameter -Wno-missing-field-initializers -Wno-array-bounds -Wno-switch -Wno-char-subscripts -Wno-unused-label -Wno-parentheses -Wno-maybe-uninitialized -std=gnu89 -fno-inline-small-functions -fno-inline-functions-called-once -fno-ipa-cp -fno-ipa-icf -fno-clone-functions -fno-reorder-functions -fno-reorder-blocks-and-partition -fno-aggressive-loop-optimizations --param=max-inline-insns-single=450 -g -gdwarf-2 -gstrict-dwarf -std=gnu89 -D_TS_ERRNO -DNATIVE_BUILD -DTEXT_DOMAIN="SUNW_OST_OSLIB" -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/inc -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/common/svc -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libuutil/common -I/home/brian/Development/arm64-gate/illumos-gate/proto/root_aarch64/usr/include -DPIC -D_REENTRANT -c -o pics/lowlevel.o /home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/common/lowlevel.c 
/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/common/lowlevel.c:57:10: fatal error: libzonecfg.h: No such file or directory
   57 | #include <libzonecfg.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
+ /opt/gcc-7/bin/gcc -fident -finline -fno-inline-functions -fno-builtin -fno-asm -fdiagnostics-show-option -nodefaultlibs -D__sun -O -m32 -fpic -Wall -Wextra -Werror -Wno-missing-braces -Wno-sign-compare -Wno-unknown-pragmas -Wno-unused-parameter -Wno-missing-field-initializers -Wno-array-bounds -Wno-switch -Wno-char-subscripts -Wno-unused-label -Wno-parentheses -Wno-maybe-uninitialized -std=gnu89 -fno-inline-small-functions -fno-inline-functions-called-once -fno-ipa-cp -fno-ipa-icf -fno-clone-functions -fno-reorder-functions -fno-reorder-blocks-and-partition -fno-aggressive-loop-optimizations --param=max-inline-insns-single=450 -g -gdwarf-2 -std=gnu89 -D_TS_ERRNO -DNATIVE_BUILD -DTEXT_DOMAIN="SUNW_OST_OSLIB" -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/inc -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/common/svc -I/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libuutil/common -I/home/brian/Development/arm64-gate/illumos-gate/proto/root_aarch64/usr/include -DPIC -D_REENTRANT -c -o /tmp/cw.0Tai7g/cw1TaG7g.o /home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/common/lowlevel.c 
/home/brian/Development/arm64-gate/illumos-gate/usr/src/lib/libscf/common/lowlevel.c:57:10: fatal error: libzonecfg.h: No such file or directory
 #include <libzonecfg.h>
          ^~~~~~~~~~~~~~
compilation terminated.
*** Error code 1
make: Warning: Command failed for target `pics/lowlevel.o'

...

make: Warning: Target `bldtools' not remade because of errors
Current working directory /home/brian/Development/arm64-gate/illumos-gate/usr/src
*** Error code 1
make: Fatal error: Command failed for target `/home/brian/Development/arm64-gate/stamps/sgs-stamp'
```

### CODE REVIEW

**Review by richlowe — CHANGES_REQUESTED** [review]
I see what you're trying to fix, but I think this is the wrong way around.

Right now we're building tools for the machine the build is running on, and ideally we want to be using the headers and libraries from the build machine, what this was doing before was wrong because it was -- at least -- doing `-I$(ROOTHDR)` when that's definitely not ok because the headers and libc often need to match, and this will break that.

I think what we need is to not pass `-I $(ROOTHDRDIR)` in `CPPFLAGS` at all (or `$(SRC)/head` as in your change), and you need `pkg:/system/zones/internal` on your build machine (this used to be a hard requirement for other things.  I didn't realize it had gone away, or I'd have documented it.  Sorry)

**Comment by b-man** [comment]
Thank you for the correction and detailed explanation.

I'm very new to the code base and had a feeling that my initial approach wasn't optimal. :-)

I've pushed your recommended change (and installed that missing package) and can confirm that the build error has gone away on my end.

I'll also open a PR later today to document that dependency in arm64-gate/README.md.

**Review by richlowe — APPROVED** [review]
Thanks for this!  I'll merge it in a moment.

**Comment by richlowe** [comment]
Merged.  Thanks!

**Pull request closed without merging**
